---
# Issuer & CA Certificate for linkerd identity
apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: linkerd-ca-issuer
  namespace: linkerd
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: linkerd-ca
  namespace: linkerd
spec:
  secretName: linkerd-identity-issuer-tls
  # TODO: verify if cert rotation fully works with linkerd (min duration: 1h)
  duration: 8760h # 365d
  issuerRef:
    name: linkerd-ca-issuer
    kind: Issuer
  commonName: identity.linkerd.cluster.local
  isCA: true
  keyAlgorithm: ecdsa
  keySize: 256
---
# Issuer & Certificate for APIService and mutating/validating webhooks
apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: linkerd-apiservice-cert-issuer
  namespace: linkerd
spec:
  ca:
    secretName: linkerd-identity-issuer-tls
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: linkerd-apiservice-tls
  namespace: linkerd
spec:
  secretName: linkerd-apiservice-tls
  issuerRef:
    name: linkerd-apiservice-cert-issuer
    kind: Issuer
  duration: 2160h # 90d
  dnsNames:
  - linkerd-proxy-injector
  - linkerd-proxy-injector.linkerd
  - linkerd-proxy-injector.linkerd.svc
  - linkerd-proxy-injector.linkerd.cluster.local
  - linkerd-sp-validator
  - linkerd-sp-validator.linkerd
  - linkerd-sp-validator.linkerd.svc
  - linkerd-sp-validator.linkerd.cluster.local
  - linkerd-tap
  - linkerd-tap.linkerd
  - linkerd-tap.linkerd.svc
  - linkerd-tap.linkerd.cluster.local
