---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: linkerd-cert-sync
  namespace: linkerd

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: linkerd-cert-sync
  namespace: linkerd
rules:
- apiGroups: [""]
  resources: ["secrets", "configmaps"]
  verbs: ["get", "create", "patch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: linkerd-cert-sync
  namespace: linkerd
subjects:
- kind: ServiceAccount
  name: linkerd-cert-sync
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: linkerd-cert-sync
  apiGroup: rbac.authorization.k8s.io
