apiVersion: helm.kustomize.mgoltzsche.github.com/v1
kind: ChartRenderer
metadata:
  name: linkerd
  namespace: linkerd
chart: github.com/linkerd/linkerd2//charts/linkerd2?ref=stable-2.6.0
# TODO: add cert file values - not feasible declaratively :(
valueFiles:
- values-ha.yaml
- values.yaml
exclude:
- apiVersion: v1
  kind: Namespace
  name: linkerd
- apiVersion: v1
  kind: Secret
  name: linkerd-identity-issuer
- apiVersion: v1
  kind: Secret
  name: linkerd-proxy-injector-tls
- apiVersion: v1
  kind: Secret
  name: linkerd-sp-validator-tls
- apiVersion: v1
  kind: Secret
  name: linkerd-tap-tls
- apiVersion: v1
  kind: ConfigMap
  name: linkerd-config
