apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: linkerd-dashboard-cert
spec:
  secretName: linkerd-dashboard-tls
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  commonName: linkerd.example.org
  dnsNames:
  - $(LINKERD_DASHBOARD_HOST)
  issuerRef:
    name: cluster-ca-issuer
    kind: ClusterIssuer
