generators:
- linkerd-chart.yaml

resources:
- namespace.yaml
- linkerd-configmap-tpl.yaml
- cert-rotator-rbac.yaml
- cert-rotator-cronjob.yaml

patchesJson6902:
- target:
    group: apiregistration.k8s.io
    version: v1
    kind: APIService
    name: v1alpha1.tap.linkerd.io
  path: cabundle-apiservice-patch.yaml
- target:
    group: admissionregistration.k8s.io
    version: v1beta1
    kind: ValidatingWebhookConfiguration
    name: linkerd-sp-validator-webhook-config
  path: cabundle-webhook-patch.yaml
- target:
    group: admissionregistration.k8s.io
    version: v1beta1
    kind: MutatingWebhookConfiguration
    name: linkerd-proxy-injector-webhook-config
  path: cabundle-webhook-patch.yaml
- target:
    group: apps
    version: v1
    kind: Deployment
    namespace: linkerd
    name: linkerd-identity
  path: deployment-c2-trust-anchors-patch.yaml
- target:
    group: apps
    version: v1
    kind: Deployment
    namespace: linkerd
    name: linkerd-grafana
  path: deployment-c2-trust-anchors-patch.yaml
- target:
    group: apps
    version: v1
    kind: Deployment
    namespace: linkerd
    name: linkerd-prometheus
  path: deployment-c2-trust-anchors-patch.yaml
- target:
    group: apps
    version: v1
    kind: Deployment
    namespace: linkerd
    name: linkerd-controller
  path: deployment-c3-trust-anchors-patch.yaml
- target:
    group: apps
    version: v1
    kind: Deployment
    namespace: linkerd
    name: linkerd-sp-validator
  path: deployment-c2-trust-anchors-patch.yaml
- target:
    group: apps
    version: v1
    kind: Deployment
    namespace: linkerd
    name: linkerd-tap
  path: deployment-c2-trust-anchors-patch.yaml
- target:
    group: apps
    version: v1
    kind: Deployment
    namespace: linkerd
    name: linkerd-web
  path: deployment-c2-trust-anchors-patch.yaml
- target:
    group: apps
    version: v1
    kind: Deployment
    namespace: linkerd
    name: linkerd-proxy-injector
  path: deployment-c2-trust-anchors-patch.yaml
