apiVersion: v1
kind: ServiceAccount
metadata:
  name: build-pipeline
  namespace: build
secrets:
  - name: registry-deployment-push-credentials
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: build-pipeline
  namespace: build
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["list", "get", "create", "delete"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list", "watch", "get", "create", "update", "put", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: build-pipeline
  namespace: build
subjects:
- kind: ServiceAccount
  name: build-pipeline
  apiGroup: ""
roleRef:
  kind: Role
  name: build-pipeline
  apiGroup: rbac.authorization.k8s.io
