apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  creationTimestamp: null
  name: source-git
  namespace: build
spec:
  params:
  - name: url
    value: https://github.com/mgoltzsche/kustomizations.git
  type: git
status: {}
---
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  creationTimestamp: null
  name: skaffold-build-0
  namespace: build
spec:
  inputs:
    resources:
    - name: source
      outputImageDir: ""
      targetPath: ""
      type: git
  outputs:
    resources:
    - name: source
      outputImageDir: ""
      targetPath: ""
      type: git
  steps:
  - name: run-build
    image: gcr.io/k8s-skaffold/skaffold:v1.0.1
    command:
    - skaffold
    - build
    args:
    - -v=debug
    - --filename
    - skaffold.yaml
    - --profile
    - oncluster
    - --file-output
    - build.out
#    env:
#    - name: GOOGLE_APPLICATION_CREDENTIALS
#      value: /secret/kaniko-secret
    resources: {}
    volumeMounts:
    - mountPath: /tekton/.docker/config.json
      name: registry-auth
      subPath: .dockerconfigjson
    - mountPath: /etc/ssl/certs/ca-cert-registry.pem
      name: registry-auth
      subPath: ca.crt
    workingDir: /workspace/source/skaffold-pipeline
  volumes:
  - name: registry-auth
    secret:
      secretName: registry-deployment-push-credentials
---
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  creationTimestamp: null
  name: skaffold-deploy-0
  namespace: build
spec:
  inputs:
    resources:
    - name: source
      outputImageDir: ""
      targetPath: ""
      type: git
  steps:
  - name: run-deploy
    image: gcr.io/k8s-skaffold/skaffold:v1.0.1
    command:
    - skaffold
    - deploy
    args:
    - --filename
    - skaffold.yaml
    - --build-artifacts
    - build.out
    workingDir: /workspace/source
    resources: {}
---
apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  creationTimestamp: null
  name: skaffold-pipeline
  namespace: build
spec:
  resources:
  - name: source-repo
    type: git
  tasks:
  - name: skaffold-build-0-task
    resources:
      inputs:
      - name: source
        resource: source-repo
      outputs:
      - name: source
        resource: source-repo
    taskRef:
      name: skaffold-build-0
  - name: skaffold-deploy-0-task
    resources:
      inputs:
      - from:
        - skaffold-build-0-task
        name: source
        resource: source-repo
    taskRef:
      name: skaffold-deploy-0
status: {}

---
apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  name: skaffold-pipeline-run
  namespace: build
spec:
  serviceAccountName: build-pipeline
  pipelineRef:
    name: skaffold-pipeline
  resources:
    - name: source-repo
      resourceRef:
        name: source-git
