---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: linkerd-proxy-injector
  namespace: linkerd
spec:
  template:
    spec:
      containers:
      - name: linkerd-proxy
        env:
        - name: LINKERD2_PROXY_IDENTITY_TRUST_ANCHORS
          value: null
          valueFrom:
            secretKeyRef:
              key: ca.pem
              name: linkerd-identity-trust-anchors
      volumes:
      - name: tls
        secret:
          secretName: linkerd-apiservice-tls
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: linkerd-sp-validator
  namespace: linkerd
spec:
  template:
    spec:
      containers:
      - name: linkerd-proxy
        env:
        - name: LINKERD2_PROXY_IDENTITY_TRUST_ANCHORS
          value: null
          valueFrom:
            secretKeyRef:
              key: ca.pem
              name: linkerd-identity-trust-anchors
      volumes:
      - name: tls
        secret:
          secretName: linkerd-apiservice-tls
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: linkerd-tap
  namespace: linkerd
spec:
  template:
    spec:
      containers:
      - name: linkerd-proxy
        env:
        - name: LINKERD2_PROXY_IDENTITY_TRUST_ANCHORS
          value: null
          valueFrom:
            secretKeyRef:
              key: ca.pem
              name: linkerd-identity-trust-anchors
      volumes:
      - name: tls
        secret:
          secretName: linkerd-apiservice-tls
