apiVersion: apps/v1
kind: Deployment
metadata:
  name: linkerd-identity
  namespace: linkerd
spec:
  template:
    spec:
      containers:
      - name: linkerd-proxy
        env:
        - name: LINKERD2_PROXY_IDENTITY_TRUST_ANCHORS
          value: null
          valueFrom:
            secretKeyRef:
              key: ca.pem
              name: linkerd-identity-trust-anchors
        volumeMounts:
        - name: issuer-ca
          subPath: ca.pem
          mountPath: /etc/ssl/certs/ca-cert.pem
      volumes:
      - name: issuer-ca
        secret:
          secretName: linkerd-identity-trust-anchors
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: linkerd-controller
  namespace: linkerd
spec:
  template:
    spec:
      containers:
      - name: linkerd-proxy
        env:
        - name: LINKERD2_PROXY_IDENTITY_TRUST_ANCHORS
          value: null
          valueFrom:
            secretKeyRef:
              key: ca.pem
              name: linkerd-identity-trust-anchors
        volumeMounts:
        - name: issuer-ca
          subPath: ca.pem
          mountPath: /etc/ssl/certs/ca-cert.pem
      volumes:
      - name: issuer-ca
        secret:
          secretName: linkerd-identity-trust-anchors
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: linkerd-web
  namespace: linkerd
spec:
  template:
    spec:
      containers:
      - name: linkerd-proxy
        env:
        - name: LINKERD2_PROXY_IDENTITY_TRUST_ANCHORS
          value: null
          valueFrom:
            secretKeyRef:
              key: ca.pem
              name: linkerd-identity-trust-anchors
        volumeMounts:
        - name: issuer-ca
          subPath: ca.pem
          mountPath: /etc/ssl/certs/ca-cert.pem
      volumes:
      - name: issuer-ca
        secret:
          secretName: linkerd-identity-trust-anchors
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: linkerd-prometheus
  namespace: linkerd
spec:
  template:
    spec:
      containers:
      - name: linkerd-proxy
        env:
        - name: LINKERD2_PROXY_IDENTITY_TRUST_ANCHORS
          value: null
          valueFrom:
            secretKeyRef:
              key: ca.pem
              name: linkerd-identity-trust-anchors
        volumeMounts:
        - name: issuer-ca
          subPath: ca.pem
          mountPath: /etc/ssl/certs/ca-cert.pem
      volumes:
      - name: issuer-ca
        secret:
          secretName: linkerd-identity-trust-anchors
---
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: linkerd-grafana
  namespace: linkerd
spec:
  template:
    spec:
      containers:
      - name: linkerd-proxy
        env:
        - name: LINKERD2_PROXY_IDENTITY_TRUST_ANCHORS
          value: null
          valueFrom:
            secretKeyRef:
              key: ca.pem
              name: linkerd-identity-trust-anchors
        volumeMounts:
        - name: issuer-ca
          subPath: ca.pem
          mountPath: /etc/ssl/certs/ca-cert.pem
      volumes:
      - name: issuer-ca
        secret:
          secretName: linkerd-identity-trust-anchors
