apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: registry-cert
spec:
  secretName: $(CERT_SECRET_NAME)
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  commonName: registry.example.org
  dnsNames:
  - $(COMMON_NAME)
  #- $(SERVICE_NAME)
  #- $(SERVICE_NAME).$(SERVICE_NAMESPACE).svc
  issuerRef:
    name: registry-issuer
    kind: Issuer
