---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: registry-credential-rotator
  labels:
    app: registry
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: registry-credential-rotator
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["list", "get", "create", "update", "put"]
- apiGroups: ["batch"]
  resources: ["cronjobs"]
  verbs: ["list", "get", "patch", "update", "put"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: registry-credential-rotator
subjects:
- kind: ServiceAccount
  name: registry-credential-rotator
  apiGroup: ""
roleRef:
  kind: Role
  name: registry-credential-rotator
  apiGroup: rbac.authorization.k8s.io
