apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: $(DEPLOYMENT_NAME)
  template:
    metadata:
      labels:
        app: $(DEPLOYMENT_NAME)
    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: 60
      containers:
      - name: registry
        image: registry:2
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
        volumeMounts:
        - name: images
          mountPath: /var/lib/registry
#        - mountPath: /certs
#          name: certs
#        - mountPath: /auth
#          name: auth
        env:
        - name: REGISTRY_HTTP_ADDR
          value: 127.0.0.1:5000
        - name: REGISTRY_HTTP_RELATIVEURLS # required when behind proxy
          value: "true"
#        - name: REGISTRY_AUTH
#          value: "htpasswd"
#        - name: REGISTRY_AUTH_HTPASSWD_REALM
#          value: "Registry Realm"
#        - name: REGISTRY_AUTH_HTPASSWD_PATH
#          value: /auth/htpasswd
#        - name: REGISTRY_HTTP_TLS_CERTIFICATE
#          value: /certs/fullchain.pem
#        - name: REGISTRY_HTTP_TLS_KEY
#          value: /certs/privkey.pem
      - name: nginx
        image: nginx:1.17-alpine
        ports:
        - name: https
          containerPort: 443
        - name: http
          containerPort: 80
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
        volumeMounts:
        - name: nginx-conf
          mountPath: /etc/nginx
        - name: cert
          mountPath: /etc/nginx/tls
        - name: auth
          mountPath: /etc/nginx/auth
      volumes:
      - name: images
        persistentVolumeClaim:
          claimName: registry-pvc
          readOnly: false
      - name: nginx-conf
        configMap:
          name: registry-nginx-conf
      - name: cert
        secret:
          secretName: $(CERT_SECRET_NAME)
      - name: auth
        secret:
          secretName: $(DEPLOYMENT_NAME)-htpasswd
