apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: registry-ingress
spec:
  rules:
  - host: $(COMMON_NAME)
    http:
      paths:
      - backend:
          serviceName: registry
          servicePort: http
        path: /
  tls:
  - hosts:
      - $(COMMON_NAME)
    secretName: $(CERT_SECRET_NAME)
