# A docker registry with TLS and basic auth using nginx.
# Related links:
# - https://kubernetes.io/docs/concepts/containers/images/#using-a-private-registry
# - https://docs.docker.com/registry/recipes/nginx/
# - https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/

resources:
  - docker-auth
  - certificate.yaml
  - credential-rotator-serviceaccount.yaml
  - credential-rotator-cronjob.yaml
  - registry-pvc.yaml
  - registry-deployment.yaml
  - registry-service.yaml
  - registry-ingress.yaml
  - auth-ingress.yaml
  - registry-clusterip-injector-daemonset.yaml

configMapGenerator:
- name: registry-nginx-conf
  files:
    - nginx.conf
#- name: registry-conf
#  files:
#    - config.yml

configurations:
- kustomizeconfig/certificate.yaml

vars:
- name: SERVICE_NAMESPACE
  objref:
    kind: Service
    name: registry
    apiVersion: v1
  fieldref:
    fieldpath: metadata.namespace
- name: SERVICE_NAME
  objref:
    kind: Service
    name: registry
    apiVersion: v1
  fieldref:
    fieldpath: metadata.name
- name: COMMON_NAME
  objref:
    kind: Certificate
    name: registry-cert
    apiVersion: cert-manager.io/v1alpha2
  fieldref:
    fieldpath: spec.commonName
- name: CERT_SECRET_NAME
  objref:
    kind: Certificate
    name: registry-cert
    apiVersion: cert-manager.io/v1alpha2
  fieldref:
    fieldpath: metadata.name
- name: DEPLOYMENT_NAME
  objref:
    kind: Deployment
    name: registry-deployment
    apiVersion: apps/v1
  fieldref:
    fieldpath: metadata.name
- name: CRON_NAME
  objref:
    kind: CronJob
    name: registry-credential-rotator-cron
    apiVersion: batch/v1beta1
  fieldref:
    fieldpath: metadata.name

configurations:
- kustomizeconfig/certificate.yaml
