# see https://github.com/zalando/postgres-operator/blob/v1.2.0/manifests/minimal-postgres-manifest.yaml
apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: pg-cluster
  namespace: apps
spec:
  teamId: pg
  volume:
    size: 500Mi
    #storageClass: csi-rbd
  numberOfInstances: 1
  users:
    coreadmin:  # database owner
    - superuser
    - createdb
    hydra: []  # role for application hydra
  databases:
    hydra: hydra  # dbname: owner
  enableMasterLoadBalancer: false
  enableReplicaLoadBalancer: false
  postgresql:
    version: "11"
  tls:
    secretName: $(PG_CLUSTER)-tls
