apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: host-rbd-link-daemonset
  namespace: rook-ceph
spec:
  template:
    metadata:
      labels:
        run-once-daemonset: host-rbd-link-daemonset
    spec:
      containers:
      - name: host-rbd-link-daemonset
        image: alpine:3.10
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh", "-c"]
        args:
        - |
            set -ex
            echo $'#!/bin/sh\n[ "`cat /tmp/status`" = linked ] || (echo -n `tail -n1 /tmp/status`; false)' >/tmp/ready
            chmod +x /tmp/ready
            if [ ! -d /host/host/dev ]; then
              echo "/host/dev dir not found! Either node is not a container or host's /dev dir is not mounted" >/tmp/status
              sleep 15
              exit 1
            fi
            i=0
            while [ $i -lt "$CEPH_MAX_RBD" ]; do
              [ -b /host/dev/rbd$i -o -L /host/dev/rbd$i ] ||
                ln -s ../host/dev/rbd$i /host/dev/rbd$i
              [ -b /host/dev/nbd$i -o -L /host/dev/nbd$i ] ||
                ln -s ../host/dev/nbd$i /host/dev/nbd$i
              i=$(expr $i + 1)
            done
            echo linked > /tmp/status
            while true; do sleep 86400; done
        env:
        - name: CEPH_MAX_RBD
          value: "50"
        readinessProbe:
          exec:
            command:
              - /tmp/ready
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
        - name: host
          mountPath: /host
          readOnly: false
      terminationGracePeriodSeconds: 0
      volumes:
      - name: host
        hostPath:
          path: /
