generators:
- linkerd-chart.yaml

resources:
- namespace.yaml
- certificates.yaml
- linkerd-configmap-tpl.yaml
- cert-sync-rbac.yaml
- cert-sync.yaml

patchesStrategicMerge:
- patches/proxy-use-identity-ca.yaml
- patches/apiserviceconfig-annotate-cabundle.yaml
- patches/apiservice-use-cert-secrets.yaml
