apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    linkerd.io/created-by: linkerd/helm stable-2.6.0
  labels:
    linkerd.io/control-plane-component: controller
    linkerd.io/control-plane-ns: linkerd
  name: linkerd-config-tpl
  namespace: linkerd
data:
  global: |
    {
      "linkerdNamespace": "linkerd",
      "cniEnabled": false,
      "version": "stable-2.6.0",
      "identityContext":{
        "trustDomain": "cluster.local",
        "trustAnchorsPem": "replace-ca-crt",
        "issuanceLifeTime": "86400s",
        "clockSkewAllowance": "20s"
      },
      "autoInjectContext": null,
      "omitWebhookSideEffects": false,
      "clusterDomain": "cluster.local"
    }
  install: |
    {
      "uuid":"36137e9b-df02-4b70-adc9-48ad91c868a5",
      "cliVersion":"stable-2.6.0",
      "flags":[]
    }
  proxy: |
    {
      "proxyImage":{
        "imageName":"gcr.io/linkerd-io/proxy",
        "pullPolicy":"IfNotPresent"
      },
      "proxyInitImage":{
        "imageName":"gcr.io/linkerd-io/proxy-init",
        "pullPolicy":"IfNotPresent"
      },
      "controlPort":{
        "port": 4190
      },
      "ignoreInboundPorts":[],
      "ignoreOutboundPorts":[],
      "inboundPort":{
        "port": 4143
      },
      "adminPort":{
        "port": 4191
      },
      "outboundPort":{
        "port": 4140
      },
      "resource":{
        "requestCpu": "100m",
        "limitCpu": "1",
        "requestMemory": "20Mi",
        "limitMemory": "250Mi"
      },
      "proxyUid": 2102,
      "logLevel":{
        "level": "warn,linkerd2_proxy=info"
      },
      "disableExternalProfiles": true,
      "proxyVersion": "stable-2.6.0",
      "proxyInitImageVersion": "v1.1.0"
    }
