---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hydra-secret-sync

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: hydra-secret-sync
rules:
- apiGroups: [""]
  resources: ["secrets", "configmaps"]
  verbs: ["get", "create", "patch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: hydra-secret-sync
subjects:
- kind: ServiceAccount
  name: hydra-secret-sync
  apiGroup: ""
roleRef:
  kind: Role
  name: hydra-secret-sync
  apiGroup: rbac.authorization.k8s.io
