apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: docker-registry-cert
  namespace: docker-registry
spec:
  secretName: docker-registry-tls-ignored
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  commonName: registry.example.org
  dnsNames:
  - $(COMMON_NAME)
  - $(SERVICE_NAME)
  - $(SERVICE_NAME).$(SERVICE_NAMESPACE).svc
  issuerRef:
    name: registry-ca-issuer
    kind: Issuer
