# see https://kubernetes.io/docs/concepts/containers/images/#using-a-private-registry
# and https://docs.docker.com/registry/recipes/nginx/
# and https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
resources:
  - namespace.yaml
  - registry-ca-certificate.yaml
  - registry-ca-issuer.yaml
  - certificate.yaml
  - rbac.yaml
  - htpasswd-generator-job.yaml
  - deployment.yaml
  - service.yaml
  - registry-clusterip-injector-daemonset.yaml
  - registry-cert-injector-daemonset.yaml
  - test/rbac.yaml
  - test/registry-push-test.yaml
  - test/registry-pull-test.yaml
  #- ingress.yaml

configMapGenerator:
- name: registry-nginx-conf
  namespace: docker-registry
  files:
    - nginx.conf

vars:
- name: SERVICE_NAMESPACE
  objref:
    kind: Service
    name: docker-registry
    apiVersion: v1
  fieldref:
    fieldpath: metadata.namespace
- name: SERVICE_NAME
  objref:
    kind: Service
    name: docker-registry
    apiVersion: v1
  fieldref:
    fieldpath: metadata.name
- name: COMMON_NAME
  objref:
    kind: Certificate
    name: docker-registry-cert
    namespace: docker-registry
    apiVersion: certmanager.k8s.io/v1alpha1
  fieldref:
    fieldpath: spec.commonName
- name: DEPLOYMENT_NAME
  objref:
    kind: Deployment
    name: docker-registry
    apiVersion: extensions/v1beta1
  fieldref:
    fieldpath: metadata.name

configurations:
- kustomizeconfig/certificate.yaml
