apiVersion: v1
kind: Service
metadata:
  name: docker-auth
spec:
  type: ClusterIP
  ports:
    - port: 5001
      targetPort: 5001
      protocol: TCP
      name: http
  selector:
    app: docker-auth
