bases:
  # TODO: pin version once 1.16 fix gets released: https://github.com/zalando/postgres-operator/issues/674
  - github.com/zalando/postgres-operator/manifests

resources:
  - namespace.yaml

namespace: postgres-operator

images:
- name: registry.opensource.zalan.do/acid/postgres-operator
  newTag: latest # v1.2.0 + k8s 1.16 fix
