# see https://kubernetes.github.io/ingress-nginx/deploy/baremetal/
apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx
spec:
  type: NodePort
  ports:
    - name: http
      nodePort: 80
      port: 80
      targetPort: 80
      protocol: TCP
    - name: https
      nodePort: 443
      port: 443
      targetPort: 443
      protocol: TCP
  externalTrafficPolicy: Cluster
