apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1alpha1.tap.linkerd.io
  namespace: linkerd
  annotations:
    certmanager.k8s.io/inject-apiserver-ca: "true"
    certmanager.k8s.io/inject-ca-from: linkerd/linkerd-identity-issuer
spec:
  caBundle: null
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: linkerd-sp-validator-webhook-config
  namespace: linkerd
  annotations:
    certmanager.k8s.io/inject-apiserver-ca: "true"
    certmanager.k8s.io/inject-ca-from: linkerd/linkerd-identity-issuer
webhooks:
- name: linkerd-sp-validator.linkerd.io
  clientConfig:
    caBundle: null
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: linkerd-proxy-injector-webhook-config
  namespace: linkerd
  annotations:
    certmanager.k8s.io/inject-apiserver-ca: "true"
    certmanager.k8s.io/inject-ca-from: linkerd/linkerd-identity-issuer
webhooks:
- name: linkerd-proxy-injector.linkerd.io
  clientConfig:
    caBundle: null
