# env vars are replaced by dex apparently
issuer: https://dex.example.org/dex
storage:
  type: kubernetes
  config:
    inCluster: true
web:
  https: 0.0.0.0:5556
  tlsCert: /etc/dex/tls/tls.crt
  tlsKey: /etc/dex/tls/tls.key

connectors:
- type: github
  id: github
  name: GitHub
  config:
    clientID: $GITHUB_CLIENT_ID
    clientSecret: $GITHUB_CLIENT_SECRET
    redirectURI: https://dex.example.org/dex/callback
    org: kubernetes

logger:
  level: info

oauth2:
  skipApprovalScreen: true

staticClients:
- id: k8s-authenticator
  name: k8s-authenticator
  secret: "pUBnBOY80SnXgjibTYM9ZWNzY2xreNGQok"
  redirectURIs:
  - https://login.example.org/callback/k8s-authenticator
- id: oauth2-proxy
  name: 'OAuth2 proxy'
  secret: Oc6q03GaX4Wcd88nlzn6xgsh
  redirectURIs:
  - 'http://oauth2-proxy'
  trustedPeers:
  - oauth2

enablePasswordDB: true
staticPasswords:
- email: "admin@example.org"
  # bcrypt hash of the string "password"
  hash: "$2a$10$2b2cU8CPhOTaGrs1HRQuAueS7JTT5ZHsHSzYiFPm1leZck7Mc8T4W"
  username: "admin"
  userID: "08a8684b-db88-4b73-90a9-3cd1661f5466"
