apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: cluster-ca-key-pair
  namespace: cert-manager
spec:
  secretName: cluster-ca-key-pair
  duration: 43800h # 5y
  issuerRef:
    name: selfsigning-issuer
    kind: ClusterIssuer
  commonName: "ca.cert.cluster"
  isCA: true
